name: regulatory_api
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.19
  - pip=25.3
  - setuptools=80.10.2
  - wheel=0.46.3
  - ca-certificates=2025.12.2
  - certifi=2026.01.04
  - openssl=3.0.19
  - bzip2=1.0.8
  - libzlib=1.3.1
  - zlib=1.3.1
  - xz=5.6.4
  - sqlite=3.51.1
  - expat=2.7.4
  - libexpat=2.7.4
  - libffi=3.4.4
  - annotated-doc=0.0.4
  - annotated-types=0.6.0
  - anyio=4.10.0
  - brotlicffi=1.2.0.0
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.2.1
  - colorama=0.4.6
  - dnspython=2.8.0
  - email-validator=2.3.0
  - exceptiongroup=1.3.0
  - fastapi=0.128.0
  - fastapi-cli=0.0.20
  - fastapi-core=0.128.0
  - h11=0.16.0
  - httpcore=1.0.9
  - httptools=0.7.1
  - httpx=0.28.1
  - idna=3.11
  - jinja2=3.1.6
  - loguru=0.7.3
  - markdown-it-py=4.0.0
  - markupsafe=3.0.2
  - mdurl=0.1.2
  - packaging=25.0
  - pydantic=2.12.4
  - pydantic-core=2.41.5
  - pydantic-extra-types=2.11.0
  - pydantic-settings=2.12.0
  - pygments=2.19.2
  - pysocks=1.7.1
  - python-dotenv=1.2.1
  - python-multipart=0.0.22
  - pyyaml=6.0.3
  - requests=2.32.5
  - rich=14.2.0
  - rich-toolkit=0.17.1
  - shellingham=1.5.4
  - sniffio=1.3.1
  - starlette=0.47.3
  - tomli=2.4.0
  - typer=0.20.0
  - typer-slim=0.20.0
  - typer-slim-standard=0.20.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025c
  - urllib3=2.6.3
  - uvicorn=0.40.0
  - uvicorn-standard=0.40.0
  - watchfiles=1.1.1
  - websockets=15.0.1
  - yaml=0.2.5
  - pycparser=2.23
  - pip:
      - pymupdf==1.26.7
      - gunicorn==21.2.0  # 添加这一行      
